### PR TITLE
mix compatibility

### PR DESCRIPTION
**Pull request by tim2CF**
With mix utility Gradualizer can be used by Elixir developers.

### CODE REVIEW

**Comment by tim2CF** [comment]
@gomoripeti merge? :)

**Comment by gomoripeti** [comment]
thanks for the PR but I think any contribution should go towards the main repo (https://github.com/josefs/Gradualizer)

So how do Elixir devs would use Gradualizer exactly?
I am asking because I added erlang.mk as a build tool. So is it an acceptable workflow for now to:
```
make app
make shell
> gradualizer:type_check_module('Elixir.MyApp.MyMod').
```
The disadvantage is that the command has to be executed in the Erlang shell not Elixir. (It would be easy to add a make target like `make iex` to have the Elixir shell with the code path. Or later there could be a self-containing escript just like for `dialyzer`)

- I wouldn't use two build tools in the same project (erlang.mk and mix)
- I wouldn't add app and sup as this is a library application.
- adding `type_check_module` is a very good idea (I am about to add `type_check_dir`)

**Comment by tim2CF** [comment]
> So how do Elixir devs would use Gradualizer exactly?

I'm gonna to implement `mix task` wrapper around Gradualizer in this repo
https://github.com/coingaming/crystal
It will be something like Dialyxir wrapper around Dialyzer - because interface for developers should be simple, nobody would like to specify explicit modules or files to check :)

For example Dialyxir requires only one command: `mix dialyzer` - and it will do all automatically (build PLTs and check all modules in project)

**Comment by tim2CF** [comment]
Ok, so, I close this PR and open new one to https://github.com/josefs/Gradualizer

**Comment by gomoripeti** [comment]
A mix task is a good idea and convenient solution.
I think Mix supports erlang.mg dependencies so there is no need for a mix.exs in gradualizer.
Also having a quick look at Dialyxir, with the `runtime: false` option you don't need an app and sup file. (https://github.com/jeremyjh/dialyxir/blob/master/lib/dialyxir.ex#L8) (dialyzer also does not have an app and sup)
So I think the only addition needed for `crystal` to work is the `type_check_module` function.

**Comment by tim2CF** [comment]
> I think Mix supports erlang.mg dependencies

I'll investigate this and will push fixes to git, sure!

**Pull request closed without merging**
